### PR TITLE
Charles Hriczko - Added basic form, update and display code, composer libraries and tem…

### PR DESCRIPTION
**Pull request by chuckhriczko**
…plates

### CODE REVIEW

**Comment by benallfree** [comment]
Hi Charles, can you clean this up a bit by excluding the vendor folder?

**Comment by chuckhriczko** [comment]
Hello Ben,
No problem. I left it in there but I understand with composer that doesn't
need to be there. Code is cleaned up and I sent a new pull request, Is
there anything else I can do?

Thanks,
Chuck

**Comment by benallfree** [comment]
No Chuck that's it for now, thank you for the cleanup! :)

**Comment by chuckhriczko** [comment]
No problem Ben :) if you need anything else, please do let me know.

Chuck

**Pull request closed without merging**
